apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "75"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend","namespace":"form-app"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","valueFrom":{"configMapKeyRef":{"key":"DB_HOST","name":"app-config"}}},{"name":"DB_PORT","valueFrom":{"configMapKeyRef":{"key":"DB_PORT","name":"app-config"}}},{"name":"DB_USERNAME","valueFrom":{"secretKeyRef":{"key":"username","name":"postgres-ha-app"}}},{"name":"DB_NAME","valueFrom":{"secretKeyRef":{"key":"dbname","name":"postgres-ha-app"}}},{"name":"PORT","valueFrom":{"configMapKeyRef":{"key":"PORT","name":"app-config"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"postgres-ha-app"}}},{"name":"JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"JWT_SECRET","name":"secret"}}}],"image":"emanabosamra/taskio-backend:6578b5c71ad473924bf79c587aa79a3a68cc9672","livenessProbe":{"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":30,"periodSeconds":10},"name":"backend","ports":[{"containerPort":5000}],"readinessProbe":{"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":30,"periodSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}},"startupProbe":{"failureThreshold":30,"httpGet":{"path":"/health","port":5000},"periodSeconds":10}}]}}}}
    meta.helm.sh/release-name: taskio
    meta.helm.sh/release-namespace: form-app
  creationTimestamp: "2026-07-05T10:40:42Z"
  generation: 80
  labels:
    app.kubernetes.io/managed-by: Helm
  name: backend
  namespace: form-app
  resourceVersion: "3606067"
  uid: 18e50667-f376-429d-bb79-7e23801a56ab
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-08T11:28:40Z"
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: app-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: app-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-ha-app
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: dbname
              name: postgres-ha-app
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: app-config
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-ha-app
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: secret
        image: emanabosamra/taskio-backend:142c3be5f0dcbfd192a88906092d985bc3d6f878
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: backend
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2026-07-16T11:22:52Z"
    lastUpdateTime: "2026-07-16T11:22:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-07-13T23:25:45Z"
    lastUpdateTime: "2026-07-19T11:04:27Z"
    message: ReplicaSet "backend-56b4bcdcc8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 80
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
