sonar.projectKey=taskio
sonar.projectName=Taskio
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=taskio-backend/src,taskio-fronr/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.test.ts
