apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USERNAME: {{ .Values.config.dbUsername | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  PORT: {{ .Values.config.port | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.config.nextPublicApiUrl | quote }}
