apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
     
      containers:
        - name: migration

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          command:
            - npm
            - run
            - migration:run:prod
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-ha-app
                  key: username

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-ha-app
                  key: dbname

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-ha-app
                  key: password

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT_SECRET
