apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: taskio-network-policy
spec:
  podSelector: {}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow communication from pods in the same namespace
    - from:
        - podSelector: {}

    # Allow traffic from NGINX Ingress Controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx

  # Allow ALL outbound traffic
  egress:
    - {}
