apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{ .Release.Namespace }}
type: Opaque

stringData:
  JWT_SECRET:  {{ required "secret.jwtSecret is required" .Values.secret.jwtSecret | quote }}
  SUPER_ADMIN_NAME: {{ .Values.secret.superAdmin.name | quote }}
  SUPER_ADMIN_EMAIL: {{ .Values.secret.superAdmin.email | quote }}
  SUPER_ADMIN_PASSWORD:  {{ required "secret.superAdmin.password is required" .Values.secret.superAdmin.password | quote }}
