apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{ .Release.Namespace }}
type: Opaque

stringData:
  JWT_SECRET: "{{ .Values.secret.jwtSecret }}"
  SUPER_ADMIN_NAME: {{ .Values.secret.superAdmin.name | quote }}
  SUPER_ADMIN_EMAIL: {{ .Values.secret.superAdmin.email | quote }}
  SUPER_ADMIN_PASSWORD: {{ .Values.secret.superAdmin.password | quote }}
