apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: form-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      nodeSelector:
        kubernetes.io/hostname: test-worker2
     
      containers:
        - name: backend
          image: emanabosamra/taskio-backend:6578b5c71ad473924bf79c587aa79a3a68cc9672

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USERNAME

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
          startupProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
