apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
  namespace: form-app
spec:
  instances: 3

  storage:
    size: 5Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: taskio
      owner: taskio_user
