apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: form-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_DB: dGFza2lvX2Ri
  DB_PASSWORD: MTIzNA==
  JWT_SECRET: eW91cl9zdXBlcl9zZWNyZXRfa2V5X2hlcmU=
 
