apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
     
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-ha-app
                  key: username

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-ha-app
                  key: dbname

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-ha-app
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT_SECRET
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}

          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory }}
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory }}
              cpu: {{ .Values.backend.resources.limits.cpu }}
