apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backend-uploads
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
