apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.gateway.service.type }}

  selector:
    app: gateway

  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.containerPort }}
