server {
    listen 80;
    server_name _;

    location = /api/swagger-ui-bundle.js {
        proxy_pass http://taskio-backend:5000/api/swagger-ui-bundle.js;
    }
    location = /api/swagger-ui-standalone-preset.js {
        proxy_pass http://taskio-backend:5000/api/swagger-ui-standalone-preset.js;
    }
    location = /api/swagger-ui-init.js {
        proxy_pass http://taskio-backend:5000/api/swagger-ui-init.js;
    }
    location = /api/swagger-ui.css {
        proxy_pass http://taskio-backend:5000/api/swagger-ui.css;
    }
    location = /api/favicon-32x32.png {
        proxy_pass http://taskio-backend:5000/api/favicon-32x32.png;
    }
    location = /api/favicon-16x16.png {
        proxy_pass http://taskio-backend:5000/api/favicon-16x16.png;
    }
    location = /api-json {
        proxy_pass http://taskio-backend:5000/api-json;
    }

    location /api {
        rewrite ^/api(/.*)$ /api/v1$1 break;
        proxy_pass http://taskio-gateway:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://taskio-frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
