secret:
  jwtSecret: ""
  superAdmin:
    name: Super Admin
    email: super@taskio.com
    password: SuperSecret123!

config:
  nextPublicApiUrl: "http://20.47.65.42/api/v1"
backend:
  replicaCount: 2

frontend:
  replicaCount: 2

