name: Taskio Backend CI/CD

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  backend-ci-cd:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./taskio-backend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/taskio-backend:v1 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/taskio-backend:v1

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/taskio-backend:v1
            docker stop taskio-backend || true
            docker rm taskio-backend || true
            docker run -d \
              --name taskio-backend \
              --restart always \
              -p 5000:5000 \
              --env-file /home/${{ secrets.SERVER_USER }}/taskio-backend/.env \
              ${{ secrets.DOCKER_USERNAME }}/taskio-backend:v1
