name: Form Fullstack Kubernetes CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
   
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/taskio-backend:${{ github.sha }} \
          ./taskio-backend
 

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/taskio-backend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push backend image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/taskio-backend:${{ github.sha }}

      - name: Build frontend image
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_API_URL=http://${{ secrets.LOAD_BALANCER_IP }}/api/v1 \
          -t ${{ secrets.DOCKER_USERNAME }}/taskio-frontend:${{ github.sha }} \
          ./taskio-fronr


      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/taskio-frontend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
 
      - name: Push frontend image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/taskio-frontend:${{ github.sha }}
  

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            cd ~/task/k8s


            echo "Updating backend image..."

            kubectl set image deployment/backend \
            backend=${{ secrets.DOCKER_USERNAME }}/taskio-backend:${{ github.sha }} \
            -n form-app



            echo "Updating frontend image..."

            kubectl set image deployment/frontend \
            frontend=${{ secrets.DOCKER_USERNAME }}/taskio-frontend:${{ github.sha }} \
            -n form-app



            echo "Waiting for backend rollout..."

            if ! kubectl rollout status deployment/backend \
            -n form-app \
            --timeout=300s
            then

              echo "Backend deployment failed!"

              echo "========== Pods =========="
              kubectl get pods -n form-app -o wide

              echo "========== ReplicaSets =========="
              kubectl get rs -n form-app

              echo "========== Deployment =========="
              kubectl describe deployment backend -n form-app

              echo "========== Events =========="
              kubectl get events -n form-app --sort-by=.lastTimestamp

              echo "========== Backend Pods =========="
              kubectl get pods -n form-app -l app=backend

              for pod in $(kubectl get pods -n form-app -l app=backend -o jsonpath='{.items[*].metadata.name}')
              do
                  echo "========== Logs for $pod =========="
                  kubectl logs $pod -n form-app --tail=100 || true
                  kubectl logs $pod -n form-app --previous --tail=100 || true
              done

              echo "Rolling back backend..."
              kubectl rollout undo deployment/backend -n form-app

              exit 1

            fi



            echo "Waiting for frontend rollout..."

            if ! kubectl rollout status deployment/frontend \
            -n form-app \
            --timeout=120s
            then

              echo "Frontend deployment failed!"
              echo "Rolling back frontend..."

              kubectl rollout undo deployment/frontend \
              -n form-app

              exit 1

            fi



            echo "Deployment successful"



            echo "Backend rollout history:"
            kubectl rollout history deployment/backend \
            -n form-app


            echo "Frontend rollout history:"
            kubectl rollout history deployment/frontend \
            -n form-app



            echo "Current pods status:"
            kubectl get pods -n form-app
