name: Form Fullstack Kubernetes CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  gitleaks:
    if: false
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonarqube:
    if: false
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
    
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
   
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  hadolint:
    if: false
    needs: sonarqube
    name: Dockerfile Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: taskio-backend/Dockerfile

      - name: Lint Frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: taskio-fronr/Dockerfile
  
  checkov:
    needs: hadolint
    name: Helm Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./helm
          framework: helm
          soft_fail: false

  build:
    if: false
    name: Build (${{ matrix.app }})
    needs:
      - sonarqube
      - hadolint
      - checkov
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: backend
            context: ./taskio-backend
            image: taskio-backend

          - app: frontend
            context: ./taskio-fronr
            image: taskio-frontend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ${{ matrix.app }} image
        run: |
          if [ "${{ matrix.app }}" = "frontend" ]; then
            docker build --pull \
            --build-arg NEXT_PUBLIC_API_URL=http://${{ secrets.LOAD_BALANCER_IP }}/api/v1 \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
            ${{ matrix.context }}
          else
            docker build --pull \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }} \
            ${{ matrix.context }}
          fi
      - name: Scan ${{ matrix.app }} image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL
          scanners: vuln

      - name: Generate Trivy SARIF Report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
          format: sarif
          output: trivy-${{ matrix.app }}.sarif
          exit-code: '0'
          scanners: vuln

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ matrix.app }}-report
          path: trivy-${{ matrix.app }}.sarif

      - name: Push ${{ matrix.app }} image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }}

  deploy:   
    if: false
    needs: build
    runs-on: ubuntu-latest
    steps: 

      - name: Deploy with helm
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            cd ~/task
            git pull origin main
            cd helm

            helm upgrade --install taskio . \
              -f values-prod.yaml \
              -n form-app \
              --create-namespace \
              --set backend.image.tag=${{ github.sha }} \
              --set frontend.image.tag=${{ github.sha }} \
              --set secret.jwtSecret="${{ secrets.JWT_SECRET }}" \
              --wait \
              --timeout 5m \
              --atomic
